# Generated by Django 5.0.4 on 2024-05-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(choices=[('BLUE', 'BLUE'), ('BLUE_GREY', 'BLUE_GREY'), ('BROWN', 'BROWN'), ('BROWNISH_YELLOW', 'BROWNISH YELLOW'), ('GOLDEN_ORANGE', 'GOLDEN ORANGE'), ('GOLDEN_YELLOW', 'GOLDEN YELLOW'), ('GREEN', 'GREEN'), ('IVORY', 'IVORY'), ('ORANGE', 'ORANGE'), ('PALE_WHITE', 'PALE WHITE'), ('PALE_YELLOW', 'PALE_YELLOW'), ('PINK_AND_WHITE', 'PINK AND WHITE'), ('RED', 'RED'), ('STRAW', 'STRAW'), ('WHITE', 'WHITE'), ('YELLOW', 'YELLOW')], max_length=40)),
            ],
        ),
    ]
